### ISSUE TITLE
Identity extent of reification in new dataflow code

### ISSUE THREAD

**Issue by oubiwann** [USGS-EROS/lcmap-data#7]
The new version of ingest uses sequences to manage the dataflow -- using `partition`, these get partially reifed as necessary. The extent to which this is true and how this impacts the current implementation need to be explored.

This ticket is motivated by the issue reported in ticket #6.

**Comment by jmorton** [comment]
The new-new version of ingest doesn't use partition anymore. We don't have control over batch sizes, which if I understand correctly, was the motivation for using partition. I suggest we close this ticket unless there are reification concerns that come to mind with the approach just merged with master.
